#!/bin/bash
# Non-Windows RipGrep config
# ^ Shebang because bash highlighting is reasonable (if not strictly correct)
# for this file.
# TODO: Autogenerate the "actual" RC file from this plus (optionally) Windows
# config?

--type-add
gui:*.qml

--type-add
gui:*.uiml

--type-add
gui:*.xul

--type-add
gui:*.svg

--type-add
gui:*.fxml

--type-add
mvn:pom.xml

--type-add
mvn:site.xml

--type-add
mvn:installer-assembly.xml

--type-add
build:pom.xml

--type-add
build:site.xml

--type-add
build:installer-assembly.xml

--type-add
build:pom.xml

--type-add
build:site.xml

--type-add
build:installer-assembly.xml

--type-add
build:*.gradle

--type-add
build:gradle.*

--type-add
build:*.cmake

--type-add
build:CMakeLists.txt

--type-add
build:Cargo.toml

--type-add
build:build.rs

--type-add
build:*akefile

--type-add
build:go.mod

--type-add
build:pyproject.toml

--type-add
docs:*.txt

--type-add
docs:*.adoc

--type-add
docs:*.asciidoc

--type-add
docs:*.asc

--type-add
docs:*.rdoc

--type-add
docs:*.rst

--type-add
docs:Readme.*

--type-add
docs:README.*

--type-add
docs:*.markdown

--type-add
docs:*.md

--type-add
docs:*.mdown

--type-add
docs:*.mkd

--type-add
docs:*.mkdn

# Ignore Golang 'vendor' dirs
-g
!vendor/

# Use VSCode hyperlinks (TODO: would Vim links work as well?)
--hyperlink-format
vscode
