#!/bin/bash
# Non-Windows RipGrep config
# ^ Shebang because bash highlighting is reasonable (if not strictly correct)
# for this file.
# TODO: Autogenerate the "actual" RC file from this plus (optionally) Windows
# config?

--type-add
gui:*.qml

--type-add
gui:*.uiml

--type-add
gui:*.xul

--type-add
gui:*.svg

--type-add
gui:*.fxml

--type-add
mvn:pom.xml

--type-add
mvn:site.xml

--type-add
mvn:installer-assembly.xml

--type-add
build:pom.xml

--type-add
build:site.xml

--type-add
build:installer-assembly.xml

--type-add
build:pom.xml

--type-add
build:site.xml

--type-add
build:installer-assembly.xml

--type-add
build:*.gradle

--type-add
build:gradle.*

--type-add
build:*.cmake

--type-add
build:CMakeLists.txt

--type-add
build:Cargo.toml

--type-add
build:build.rs

--type-add
build:*akefile

--type-add
build:go.mod

# Ignore Golang 'vendor' dirs
-g
!vendor/
