#!/bin/bash
# The shebang is just to ensure that Vim knows how to highlight this file.

if [[ -n $CONFIG_DIR ]]; then
    notes_dir="$CONFIG_DIR/startup_notes"
    print_notes () {
        # Use a subshell to ensure that `shopt` and `unalias` do not affect
        # current settings.
        (
            shopt -s nullglob
            say yellow bold "*********************************************************"
            say yellow bold "NOTES:"
            # TODO platform- or env-specific notes?
            for f in "$notes_dir"/*; do
                # Ideally we should just use `bat`'s decorators, because
                # they're fairly nice, except when they're difficult to read.
                # Le sigh
                say cyan "Notes from '$(basename "$f")':"
                mdcat "$f"
                echo
            done
            say yellow bold "*********************************************************"
        )
    }

    mknote () {
        if [[ $# -eq 1 ]]; then
            f="$1"
        else
            f="general"
        fi
        f="$notes_dir/$f"
        $EDITOR "$f"
        cfgd_git add "$f"
    }

    delnote () {
        if [[ $# -eq 1 ]]; then
            f="$1"
        else
            say red "Must specify note file to remove!"
            return 1
        fi
        cfgd_git rm "$notes_dir/$f"
    }

    mkdir -p "$notes_dir"
    if [[ ! -v notes_printed_on_startup ]]; then
        print_notes
        notes_printed_on_startup=true
    fi
fi
