#!/bin/bash

# XXX See comment in `wsl_daemon_start` about the necessary `sudoers` change:
# ...also, this still asks for a password. Why?
# if $WSL; then
#     sudo "$CONFIG_DIR"/OS_specific/Windows/wsl_daemon_start docker
# fi

# Also need to add user to `docker` group:
# sudo usermod -a -G docker $USER
