#!/bin/bash
# The shebang is just to ensure that Vim knows how to highlight this file.

# Functions and other setup used by other public-config scripts, *including*
# `install`, *and* sourced by `.bashrc`.

# TODO add stuff here from `install` and possibly `.bashrc/.bash_rcbase`, then use it in
# those scripts

if [[ -v WINDIR ]]; then
    # Windows linking command based on http://stackoverflow.com/a/25394801/1858225
    # Ideally, in standard bash setup on Windows, this would be an alias for
    # `ln` that uses the `/h` flag if `-s` is not given as an argument.
    win_symlink() {
        if [[ $# -ne 2 ]]; then
            echo "ERROR: 'win_symlink' requires *two* arguments!" >&2
            # Currently, we *exit* with *error*...because this is a script bug.
            exit 1
        fi
        target="$(cygpath -w "${1}")"
        new_link="$(cygpath -w "${2}")"
        echo "Making symlink: ${new_link} -> ${target}"
        # Windows needs to be told if it's a directory or not. Infer that.
        # Cygpath should already have performed the directory-separator conversion.
        if [[ -d "$target" ]]; then
            cmd <<< "mklink /D \"$new_link\" \"$target\"" > /dev/null
        else
            cmd <<< "mklink \"$new_link\" \"$target\"" > /dev/null
        fi
    }
fi
