#!/bin/bash
# The shebang is just to ensure that Vim knows how to highlight this file.

known_ids="kjstrand kstrand BatmanAoD batmanaod"
id_is_known=false
primary_local_account=
primary_HOME=

if [[ -r /usr/libexec/path_helper ]]; then
    # Not sure why this isn't done by default for non-login shells on OS X.
    eval $(/usr/libexec/path_helper)
fi

# Ensure particular dirs are on $PATH if they exist.
# Logic to ensure path is only added *once* is taken from
# http://superuser.com/a/39995/199803
# For more PATH-editing convenience functions:
# http://superuser.com/a/1001014/199803
ensure_on_path () {
    if [[ -d "$1" ]] && [[ ":$PATH:" != *":$1:"* ]]; then
        export PATH="${PATH:+"$PATH:"}$1"
    fi
}

for usrname in $known_ids; do
    if [[ $usrname == $(whoami) ]]; then
        id_is_known=true
        primary_local_account=$usrname
        primary_HOME=${HOME}
        break
    elif [[ -d $(eval echo ~${usrname} ) ]]; then
        primary_local_account=$usrname
        primary_HOME="$(eval echo ~${usrname})";
    fi
done

if [[ -n "$primary_HOME" ]]; then
    ensure_on_path "${primary_HOME}/bin"
    ensure_on_path "${primary_HOME}/.cargo/bin"
fi
# Either way, add the current-user's binaries
ensure_on_path "${HOME}/bin"
ensure_on_path "${HOME}/.cargo/bin"

# For Yarn (TODO: do I have some standard way of doing this?)
ensure_on_path "$HOME/.yarn/bin"
ensure_on_path "$HOME/.config/yarn/global/node_modules/.bin"

# TODO move all platform-checking logic to `bootstrap`
WINDOWS=false
CYGWIN=false
WSL=false   # Linux Subsystem on Windows
# See https://stackoverflow.com/a/43618657/1858225
if grep -qE "(Microsoft|WSL)" /proc/version &>/dev/null; then
    # TODO set WINDOWS=true?
    WSL=true
    # TODO check if X11 server is running somehow? (xset? not installed by
    # default...)
    export DISPLAY=:0.0
# Alternate:
# if grep -q '_NT-' <(uname -s); then
elif [[ -d "$WINDIR" ]]; then
    WINDOWS=true
    # Cygwin-specific oddities
    if grep -q Cygwin <(uname -o); then
        CYGWIN=true
        # Don't get fooled by the carriage-return character.
        export SHELLOPTS
        set -o igncr
        CDPATH=/cygdrive/c/:/cygdrive/c/Users/kjstrand/
    fi
    # TODO: if using Git-Bash, fix `ln`!! (See `install` script)
fi

if [[ -n "$primary_HOME" ]]; then
    # Check that I have the rest of my "public-config" stuff.
    CONFIG_DIR="${primary_HOME}/public-config"
    # TODO consider looking for private-config, too
    alias cfgd_git="git --git-dir $CONFIG_DIR/.git"
    if [[ ! -d $CONFIG_DIR ]]; then
        echo "WARNING: public config directory not found!" >&2
        CONFIG_DIR=
        unalias cfgd_git
    elif grep -v -q -i 'batmanaod' \
    <(cfgd_git config --get remote.origin.url \
    2>/dev/null); then
        echo "WARNING: this bash config designed for use in conjunction" >&2
        echo "with the other config files in the BatmanAoD/public-config" >&2
        echo "git repository." >&2
        unalias cfgd_git
    else
        git_remote_head="$(timeout 1s cfgd_git \
            ls-LINUX_NATIVE origin -h refs/heads/master 2>/dev/null)"
        if [[ -n "$git_remote_head" ]]; then
            if [[ "$(cfgd_git rev-parse HEAD \
                    2>/dev/null)" != \
                "$(echo ${git_remote_head} | awk '{print $1}')" ]]; then
                echo "WARNING: local public config repo is not in sync with github!!" >&2
            fi
        fi
    fi
fi

# If '${primary_HOME}/Public' is empty, delete it. I NEVER use it, and it's mostly just
# annoying.
if [[ -n "${primary_HOME}" && -n "$CONFIG_DIR" && -d "${primary_HOME}/Public" && -z $(ls -A "${primary_HOME}/Public") ]]; then
    rmdir "${primary_HOME}/Public"
fi

# LINUX_NATIVE is set in the `bootstrap` script
if $LINUX_NATIVE; then
    if [[ -n "${primary_HOME}" ]]; then
        # Currently using xmodmap instead of xkbmap
        if [[ -r "${primary_HOME}/.Xmodmap" ]]; then
            xmodmap "${primary_HOME}/.Xmodmap"
        else
            echo "WARNING: ${primary_HOME}/.Xmodmap not found!" >&2
        fi
    fi
    # TODO check if CAPS is configured, and if so, manually load Xmodmap? (Bug
    # in some WMs...)
    if [[ -f ${primary_HOME}/.Xkbmap ]]; then
        echo "WARNING: Use of ${primary_HOME}/.Xkbmap is deprecated!" >&2
        if [[ -n $CONFIG_DIR ]]; then
            echo "Latest keymapping customizations can be found" >&2
            echo "in $CONFIG_DIR/.Xmodmap" >&2
        fi
    fi
fi

if $LINUX_ANY; then
    sharedobj_ext=so
elif $MAC_OSX; then
    sharedobj_ext=dylib
elif $WINDOWS; then
    sharedobj_ext=dll
else
    echo "WARNING: Don't know shared-object extension for current platform!" >&2
    # Not sure what the default should be. This seems sensible.
    sharedobj_ext=so
fi

toolsbld_path="${primary_HOME}/ToolsBld"

if $id_is_known; then
    mkdir -p "${toolsbld_path}"
fi

USING_STDERRED=false
# stderred doesn't seem to work on OS X
if ! $MAC_OSX; then
    stderred_path="${toolsbld_path}/stderred"
    stderred_so="${stderred_path}/build/libstderred.$sharedobj_ext"
    if [[ -d "${stderred_path}"  && \
        -r "$stderred_so" && \
        ":$LD_PRELOAD:" != *":${stderred_path}"* ]]; then
        export LD_PRELOAD="${stderred_so}${LD_PRELOAD:+:$LD_PRELOAD}"
        USING_STDERRED=true
    fi
fi

# Convert LD_PRELOAD (if any) to the appropriate platform var (if any)
if $MAC_OSX; then
    export DYLD_INSERT_LIBRARIES="$LD_PRELOAD"
    unset LD_PRELOAD
fi

# Set information about the history files
export histchars='!^'  # Get comments saved in history
export HISTSIZE=65536
export HISTFILESIZE=${HISTSIZE}
HISTCONTROL=ignoredups:erasedups
shopt -s histappend
shopt -s checkhash
# Apparently this disables tab-completion for paths. Haha! Uuuuurgh.
# http://stackoverflow.com/q/29907892/1858225
# shopt -s nullglob
# Intentionally duplicated from bashrc
shopt -s extglob
shopt -s globstar
shopt -s autocd

# use Vim as pager.
# Disabled for now because it's actually really annoying.
# TODO: if I can figure out how to get VIM to do colors correctly, then
# I can just implement it myself without all the annoyances built in
# by whoever programmed this thing.
# export PAGER='view -S ${primary_HOME}/.vimpager'
# TODO: make a list of things that bug me about this thing, because I can't
# actually remember why I stopped using it.
#   * numbers not on by default, even though 'set nu' is in vimrc
if [[ -e ${primary_HOME}/bin/vimpager ]]; then
    PAGER=$(readlink -f ${HOMEBIN}/vimpager)
else
  PAGER="less -n -Q"
fi
export PAGER

# Force man pages to be 80 columns wide.
export MANWIDTH=80

# I'd expect there to be a way to do this in my gitconfig, but...maybe not?
export GIT_ASKPASS=

# create a personal-use tmp dir
# Do NOT export! Programs should use the standard `/tmp`!
TMP="${primary_HOME}/tmp"
if $id_is_known; then
    mkdir -p "${primary_HOME}/tmp"
fi

if [[ ! -d "$TMP" ]]; then
    TMP=/tmp
fi

# Set up options
# set -u                # attempting to expand unset variables is an error
set -o monitor          # enable job control
set -o vi               # vi command-line editing

# Workaround for a gvim/git-bash oddity.
# See https://stackoverflow.com/q/31167411/1858225
if ! $WSL && ! hash gvim 2>/dev/null && type gvim.bat &>/dev/null; then
    alias gvim=gvim.bat
fi
# XXX TODO
# How to determine if I want `nvim` or `gvim` as the default?
# This suggests that my startup scripts should be more configurable on a
# per-system basis...
if false; then # hash nvim 2>/dev/null; then
    export EDITOR=nvim
    # Custom script for launcing nvim in a new gnome terminal
    # TODO the native GUI interface for nvim should make this unnecessary
    # TODO: on WSL: must be `nvim-qt.exe` (probably this applies elsewhere?)
    if hash nvim-qt 2>/dev/null && test -n $DISPLAY; then
        # `nvim-qt` and `gvim` both have an odd problem in git-bash
        # that causes them not to fork appropriately.
        # TODO figure out a better condition here.
        if $WINDOWS; then
            export NEWWINDOW_EDIT_CMD="start nvim-qt"
            # Exploit the bug mentioned above.
            # TODO Since this is a bug, it probably isn't reliable...
            export VISUAL=nvim-qt
        else
            # Use workaround for https://github.com/equalsraf/neovim-qt/issues/148
            # ...and a weird VcXsrv issue that causes new windows to be gigantic
            export NEWWINDOW_EDIT_CMD="nvim-qt --geometry 650x800 -- --"
            # TODO check whether this is supported on Linux yet.
            # export VISUAL="nvim-qt -f"
            export VISUAL=nvim
        fi
    else
        export NEWWINDOW_EDIT_CMD=nvim
        export VISUAL=nvim
    fi
elif hash gvim 2>/dev/null; then
    # Mac may or may not be running X11.
    if [[ -n $DISPLAY || $MAC_OSX ]]; then
        export NEWWINDOW_EDIT_CMD=gvim
        export EDITOR="gvim -f"
        export VISUAL="gvim -f"
    else
        export NEWWINDOW_EDIT_CMD=vim
        export EDITOR=vim
        export VISUAL=vim
    fi
elif $WSL; then
    # XXX how to figure out the version?
    NEWWINDOW_EDIT_CMD="$(echo /mnt/c/Program\ Files\ \(x86\)/Vim/vim*/gvim.exe)"
    # XXX having spaces in the path doesn't work...
    # Maybe I just need a custom script in ~/bin/
    export EDITOR="vim -f"
    export VISUAL="vim -f"
# On Windows, git-bash will install `/usr/bin/vim` -- which is *NOT* what we
# want if we have a full Windows gVim install. Ideally, we could use the
# Windows `start` command to simply check if `gvim` is on the *Windows* PATH,
# then use something like `start /b gvim` as our $NEWWINDOW_EDIT_COMMAND, but
# for some reason the `/b` flag can't be used in git-bash.
# So we simply explicitly check for the `gvim.bat` file in the location that
# the Vim installer happens to use.
# TODO this seems brittle--there's no particular reason for the Vim installer
# to always install the batch files to C:\Windows. Re-evaluate the `start`
# situation and/or try to find another way to search the Windows PATH for gvim.
elif hash cygpath 2>/dev/null && [[ -e "$(cygpath 'C:\Windows\gvim.bat')" ]]; then
    export NEWWINDOW_EDIT_CMD="$(cygpath 'C:\Windows\gvim.bat')"
    export EDITOR="$NEWWINDOW_EDIT_CMD -f"
    export VISUAL="$NEWWINDOW_EDIT_CMD  -f"
else
    # `vi` is universal.
    export NEWWINDOW_EDIT_CMD=vi
    export EDITOR=vi
    export VISUAL=vi
fi

if $WSL; then
    # Handle symlinks: workaround for
    # https://github.com/microsoft/WSL/issues/4868
    wsl_native_args () { 
        cmd="$1";
        shift;
        args=();
            for a in "$@"; do
                if [[ -L "$a" ]]; then
                    args+=("$(abspath "$a")");
                else
                    args+=("$a");
                fi;
            done;
        "$cmd" "${args[@]}"
    }
    edit () { 
        wsl_native_args "$NEWWINDOW_EDIT_CMD" "$@"
    }
else
    edit () { "$NEWWINDOW_EDIT_CMD" "$@" ; }
fi

export PEDITOR="$EDITOR"
export EDOVER="$VISUAL"
set -o ignoreeof          # do not let CNTL-D exit the shell
shopt -s checkwinsize    # Reset LINES and COLUMNS after each command

# Inputrc settings to override
bind "set completion-ignore-case on"
bind "set show-all-if-ambiguous on"
bind Space:magic-space # ...for some reason this can't come earlier...?

add_prompt_command () {
    # Adapted from how `starship` handles this
    # A nicer way to handle this would be have a 'prompt-command-array`.... too
    # bad that's not a built-in feature, but it shouldn't be too hard to do it
    # myself.
    # TODO someone has already written this; try it out:
    # https://github.com/rcaloras/bash-preexec
    # Zsh actually does use arrays for its hooks:
    # http://zsh.sourceforge.net/Doc/Release/Functions.html#Hook-Functions
    if [[ -z "$PROMPT_COMMAND" ]]; then
        PROMPT_COMMAND="$1"
    # TODO this check is not very robust. A better way would be to split the
    # prompt-command into an array based on `;`, then check each element.
    elif [[ "$PROMPT_COMMAND" != *"$1"* ]]; then
        # Remove any trailing semicolon before appending
        PROMPT_COMMAND="${PROMPT_COMMAND%;};$1;"
    fi
}

if hash starship 2>/dev/null; then
    # TODO look into adding Kubernetes information. See
    # personal-notes/context-items.md
    # Jeff's setup:
    # https://rms.slack.com/archives/CJJ7EQ285/p1557355726002600
    # TODO `starship init bash` is re-adding the prompt-command, because it
    # assumes that `starship_precmd` comes _last_.
    # Submit a bug report for this.
    # It actually makes some sense to _want_ starship_precmd to come last,
    # but the init command should _ensure_ that rather than behaving badly if
    # it doesn't.
    # So for now, the workaround is... run the init (which generates the
    # precomd and preexec functions), then restore the previous PROMPT_COMMAND,
    # then add `starship_precmd`.
    SAVED_PROMPT_COMMAND="$PROMPT_COMMAND"
    eval "$(starship init bash)"
    PROMPT_COMMAND="$SAVED_PROMPT_COMMAND"
    add_prompt_command starship_precmd
else
    # Set the prompt
    PS1='\h|\W> '    
    # Make it cyan
    PS1="\[\e[0;36m\]${PS1}\[\e[m\]"
    # If root, make that obvious
    if [[ $(whoami) == root ]]; then
        PS1="\[\e[0;31m\]\u@\[\e[m\]${PS1}"
    elif ! ${id_is_known}; then
        PS1="\[\e[0;33m\]\u@\[\e[m\]${PS1}"
    fi
fi

# Make `less` display colors and not clear the screen
# ....not reeeeeally sure what this does...
# export LESS="-XR"

# Figure out the correct RipGrep config file.
# If the parent env has already set a config file path, use that.
if [[ -z "$RIPGREP_CONFIG_PATH" ]]; then
    RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"
    if $WINDOWS; then
        # TODO consider setting this varialbe in Windows environment
        # settings so that it works in cmd.exe.
        RIPGREP_CONFIG_PATH_win="${RIPGREP_CONFIG_PATH}_win"
        if [[ -r "$RIPGREP_CONFIG_PATH_win" ]]; then
            RIPGREP_CONFIG_PATH="$RIPGREP_CONFIG_PATH_win"
        fi
    fi
fi
if [[ -r "$RIPGREP_CONFIG_PATH" ]]; then
    export RIPGREP_CONFIG_PATH
fi

# Load completion function
if [[ -r /etc/bash_completion ]]; then
     . /etc/bash_completion
fi
if [[ -r /usr/local/etc/profile.d/bash_completion.sh ]]; then
    . /usr/local/etc/profile.d/bash_completion.sh
fi
# TODO - figure out why OS X doesn't seem to have a standard way to install
# Bash completions w/ Homebrew
if [[ -r "$HOME/.completions" ]]; then
    for completion in "$HOME/.completions"/*.bash; do
        . "$completion"
    done
fi
hash kubectl 2>/dev/null && . <(kubectl completion bash)
set completion-ignore-case on

# Maybe only works on Mac?
if [[ -x /usr/libexec/java_home ]]; then
    export JAVA_HOME="$(/usr/libexec/java_home)"
fi
